require("3rd_plugins.lazy")
vim.cmd.colorscheme("catppuccin-mocha")

require("3rd_plugins.treesitter")
require("3rd_plugins.lspconfig")
require("3rd_plugins.dap")
require("3rd_plugins.mason")
require("3rd_plugins.mason-lspconfig")
require("3rd_plugins.luasnip")
require("3rd_plugins.cmp")
require("3rd_plugins.trouble")
require("3rd_plugins.telescope")
require("3rd_plugins.lualine")
-- require("3rd_plugins.overseer")
require("3rd_plugins.oil")
require("3rd_plugins.neo_tree")
require("3rd_plugins.neovide")
require("3rd_plugins.bufferline")
require("3rd_plugins.conform")
require("3rd_plugins.flash")
